open-source-parsers/jsoncpp

test/runjsontests.py

quote cmdline arg

---

test/runjsontests.py

Quotes spaces fixed

---

src/jsontestrunner/main.cpp
src/lib_json/json_writer.cpp
test/runjsontests.py

Refactor jsontestrunner. Then run it twice for each test, for both `StyledWriter` and `StyledStreamWriter`.

Test both styled writers

---

amalgamate.py
devtools/antglob.py
devtools/batchbuild.py
devtools/fixeol.py
devtools/licenseupdater.py
devtools/tarball.py
doxybuild.py
makerelease.py
scons-tools/globtool.py
scons-tools/srcdist.py
scons-tools/substinfile.py
scons-tools/targz.py
test/cleantests.py
test/generate_expected.py
test/pyjsontestrunner.py
test/runjsontests.py
test/rununittests.py

Some python changes

---

include/json/value.h
src/lib_json/json_reader.cpp
src/lib_json/json_value.cpp

This will make it easier to fix newlines consistently.

rm trailing newlines for *all* comments

---

src/lib_json/json_writer.cpp

Seems like a big improvement. See issue #142.

proper newlines for comments

---

include/json/value.h
include/json/writer.h
src/lib_json/json_reader.cpp
src/lib_json/json_value.cpp
src/lib_json/json_writer.cpp

NewFastWriter and OldCompressingStreamWriterBuilder are no longer needed.

Favor settings in new StreamWriterBuilder

---

include/json/value.h
src/lib_json/json_value.cpp

This will let us support embedded zeroes, for UTF-8.

Store length in CZString

---

doc/jsoncpp.dox
include/json/reader.h
include/json/writer.h
src/lib_json/json_reader.cpp
src/lib_json/json_writer.cpp
src/test_lib_json/main.cpp

Many people do not like to access `settings_` directly.

Setting builders

---

include/json/value.h
src/lib_json/json_value.cpp
src/test_lib_json/main.cpp

Allow embedded zeroes in getters, with tests.

Get with zero

---

src/lib_json/json_value.cpp
src/test_lib_json/main.cpp

Same as #206, but different tests.

Fix cz string copy constructor

---

include/json/config.h

Macro deprec

---

src/lib_json/json_writer.cpp

C std headers

---

include/json/value.h
src/test_lib_json/main.cpp

Use unsigned for DuplicationPolicy

---

src/lib_json/json_writer.cpp

Hi,
I fixed a small compile error when we build jsoncpp using Android-NDK.

fix compile error on android

---

README.md

...by setting the archive directory variable

make the unix cmake example work

---

devtools/fixeol.py

Same as #299 (bca0eff81a1c5ef160d9858b8e89b1c919b71c1f), but an earlier
commit needed to be rebased.

Fix undefined name "sys"

---

include/json/reader.h
include/json/value.h
include/json/writer.h
src/lib_json/json_reader.cpp
src/lib_json/json_writer.cpp
src/test_lib_json/jsontest.h

Source : http://en.cppreference.com/w/cpp/language/override
Whoops. Was #347, but accidentally closed before merging.

C++11: override keyword

---

include/json/value.h
src/lib_json/json_valueiterator.inl
src/test_lib_json/main.cpp

Iterator conversions

---

CMakeLists.txt

http://stackoverflow.com/a/24305849/263998

Support ccache

---

src/lib_json/json_reader.cpp

instead of hard-coded message
Signed-off-by: Evince <baneyue@gmail.com>

json_reader throwRuntimeError return error details

---

include/json/assertions.h
include/json/config.h
include/json/reader.h
include/json/value.h
include/json/writer.h
src/jsontestrunner/main.cpp
src/lib_json/json_reader.cpp
src/lib_json/json_value.cpp
src/lib_json/json_valueiterator.inl
src/lib_json/json_writer.cpp
src/test_lib_json/jsontest.h
src/test_lib_json/main.cpp

JSONCPP_STRING etc.

---

include/json/value.h
src/lib_json/json_value.cpp

Resolve Issue - https://github.com/open-source-parsers/jsoncpp/issues/389

Added NORETURN for throw functions.

---

src/lib_json/json_tool.h

Fix a clang warning

---

src/lib_json/json_value.cpp

re #488 and #490
See discussion at
* https://github.com/open-source-parsers/jsoncpp/commit/0f288aecdd158cb13e16a5f76537b44df32a7d8e

Allow dtor for nullSingleton

---

src/lib_json/json_value.cpp
src/lib_json/json_writer.cpp

Avoid null for stringValue

---

src/lib_json/json_writer.cpp
src/test_lib_json/main.cpp

#546: Ensure floating point values on input render as floats on output

---

README.md

Related to issue #564, i included on README, instructions in how to use the library with Conan package manager.

Including instructions in how to use jsonCpp with conan

---

.travis.yml
meson.build
travis.sh

This may require a few iterations.

Mesonise in TravisCI

---

src/lib_json/json_writer.cpp

https://www.viva64.com/en/w/V817/print/

strstr -> strchr

---

.travis.yml
src/lib_json/json_reader.cpp

This is a simple change from @wolframroesler (who submitted #666 from unknown repo, so I could not download the commit).
(I could not merge #666 because of a problem in TravisCI. I've pushed a fix, but now TravisCI is failing for some sub-jobs and succeeding for others. Sometimes a "restart" works. Not sure what to do about this.)

Drop stderr

---

src/lib_json/json_value.cpp

Use move ctor in append()

---

src/lib_json/json_writer.cpp

Now that TravisCI is passing again, this replaces #712

replace code point in range(0xD800, 0xDFFF) to replacement mark

---

include/json/value.h
src/lib_json/json_value.cpp
src/test_lib_json/main.cpp

Value::copy() creates a deep copy now

---

doc/doxyfile.in
doc/web_doxyfile.in
include/json/config.h
include/json/writer.h
src/test_lib_json/jsontest.h

Found in downstream CMake repo via `codespell -q 3`

Misc-typos

---

include/json/writer.h

Related to #746 
Clarify the documentation regarding newline / indent behavior.

Clarify documentation regarding indentation / newline

---

src/lib_json/json_value.cpp
src/lib_json/json_writer.cpp

Minor changes for static analysis

---

src/lib_json/json_reader.cpp
src/lib_json/json_value.cpp
src/lib_json/json_writer.cpp

BORLAND compatible

---

README.md

Add information about how one can get a Meson wrap file.

Add Meson related info to README

---

amalgamate.py

I don't know why we didn't include this before.
It seems to work fine.

Issue #872: add json/allocator.h in the amalgamated header.

---

include/json/config.h
include/json/value.h
src/lib_json/json_value.cpp
src/test_lib_json/main.cpp

remove JSON_HAS_RVALUE_REFERENCES

---

src/lib_json/json_reader.cpp

This patch is a minor fix to Json::OurReader to properly check against
maxLargestInt, not maxInt. Some cleanup in the decodeNumber method is
included.

Issue #633: Fix issue with maxInt

---

src/test_lib_json/main.cpp

Change Value::null and Value::nullRef to Value::nullSingleton() in main.cpp

---

src/test_lib_json/fuzz.dict

This is just adding a dictionary file for fuzzing

Add dictionary for fuzzing

---

src/test_lib_json/main.cpp

add omitEndingLineFeed, enableYAMLCompatibility test cases in WriteTest
add indentation, enableYAMLCompatibility test cases in StreamWriterTest

Add some testcases: WriteTest, StreamWriterTest

---

src/test_lib_json/jsontest.h
src/test_lib_json/main.cpp

Fix issue #1040 
The test log :
It can regist testcase automatically.

Test Framework Modify : Remove JSONTEST_REGISTER_FIXTURE

---

.travis.yml

Issue #1038: Use Coveralls tool in project.

---

src/lib_json/json_reader.cpp
src/test_lib_json/main.cpp

update pushError for Reader and CharReader

---

src/test_lib_json/main.cpp

Add some testcases for `json_value.cpp`, include the testcases of `Path` and `PathArgument`.

Add testcases for json_value.cpp to improve coverage [90+%]

---

src/lib_json/json_reader.cpp

run clang-format

---

src/test_lib_json/main.cpp

Fix conflict: which has been modified in #1084

fix conflict

---

src/test_lib_json/main.cpp

tweak to avoid implicit narrowing warning.

---

src/lib_json/json_reader.cpp
src/test_lib_json/main.cpp

fix Reader bug and add testcase

---

AUTHORS

commits:
ff923658c4d9f1492617557148369b34c71ba623
5907cef86ca699a842d0a8cad4c018b4da5d6e17

adding myself to AUTHORS as per commits

---

src/lib_json/CMakeLists.txt

Fix the problem introduced in #1197

Hot fix for building static lib

---

include/json/version.h
src/test_lib_json/main.cpp

Version test

---

include/json/value.h

`Json::ValueIterator` operators `*` and `->` need to be const

---

pkg-config/jsoncpp.pc.in

Noticed when building from the source that the package version wasn't getting set correctly.

Fixed pkg-config Version

---

CMakeLists.txt

allow selection of Windows MSVC runtime

---

src/lib_json/json_value.cpp
src/test_lib_json/main.cpp

Fix Value::resize to fill all array elements

---

include/json/writer.h

add comment in header file for #1045

add comment for emitUTF8 in header

---

src/lib_json/json_reader.cpp

Avoid getline(s, EOF)
