CMakeLists.txt
With set(CMAKE_*_OUTPUT_DIRECTORY) when using jsoncpp as a sub project,
the parent project's executables and libraries will also be outputed to
jsoncpp's directory. By removing this, it is up to the parent projects
to decide where to put their and jsoncpp's executables and libraries.
=> CMake: Remove set(CMAKE_*_OUTPUT_DIRECTORY)

include/json/reader.h, src/lib_json/json_reader.cpp
The TODO comment in `Reader::decodeNumber()` suggests a possible optimization of the multiply-and-add loop which might be worth considering.
=> Simplify Reader::decodeNumber() / Remove unused functions

include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
See issue #28.
```
/** \brief Remove the indexed array element.
O(n) expensive operations.
Update 'removed' iff removed.
(This is a better pattern than removeMember().)
\return true iff removed (no exceptions)
*/
bool removeIndex(ArrayIndex i, Value* removed);
```
=> Remove index

src/lib_json/json_value.cpp
I was trying to bundle amalgamated JsonCpp in a project that is being built with `-Werror` and `-pedantic` and had to make this change to avoid a bitfield overflow warning:
```
CXX(target) Release/obj.target/project/third/jsoncpp.o
../third/jsoncpp.cpp: In copy constructor ‘Json::Value::Value(const Json::Value&)’:
../third/jsoncpp.cpp:1831:18: error: overflow in implicit constant conversion [-Werror=overflow]
allocated_ = true;
^
cc1plus: all warnings being treated as errors
make[2]: *** [Release/obj.target/project/third/jsoncpp.o] Error 1
```
It's kind of a silly change (so feel free to reject) but since it's the only warning emitted I thought it might be worth pulling in.
=> Build without warnings with -pedantic enabled.

CMakeLists.txt
Travis CI [does not yet support gcc-4.8, needed for c++11](https://github.com/travis-ci/travis-ci/issues/1379), so we
will try c++0x for now.
=> upgrade -std=c++ version

src/lib_json/json_value.cpp
=> Fix a border case which causes Value::CommentInfo::setComment() to crash

doc/jsoncpp.dox, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_writer.cpp, test/runjsontests.py
Here, we use a *Builder* to configure a StreamWriter more easily.
We use virtual methods to hide the implementation. But we use a concrete wrapper to hide the virtual methods. This allows us to add new methods [without bumping the major version](http://stackoverflow.com/questions/14875052/pure-virtual-functions-and-binary-compatibility), maintaining binary-compatibility.
I plan to fix #103 using this new API, but for now `operator<<()` is functionally unchanged.
We still need a plan for `FastWriter`.
See #131.
=> StreamWriterBuilder

doc/jsoncpp.dox, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_writer.cpp
This will make more sense to people.
By using 2 separate Builders, we can keep each API simple. We will agree not to add any fields, so we do not need virtual methods and wrappers. If we need new fields, we can simply provide a new Builder. No big deal.
=> Simplify builder

doc/jsoncpp.dox, include/json/reader.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
We need a version which can be augmented with binary-compatibility. So we use our own Json::Value for configuration. (#131)
=> Reimplement the new Builders

include/json/reader.h, src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
Bad input should not cause seg-fault.
=> Stack limit

include/json/reader.h, src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
=> Fail if extra

include/json/value.h, src/lib_json/json_valueiterator.inl, src/test_lib_json/main.cpp
=> Fix bug in ValueIteratorBase::operator- 

include/json/assertions.h
JSON_ASSERT now throws a runtime_error
=> only throws exceptions JSON_USE_EXCEPTION

include/json/reader.h, src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
=> Allow single quote

src/test_lib_json/main.cpp
This verifies the behavior of `StaticString`. I have no idea how popular this feature is, but we need to ensure that we do not break it when we fully support UTF-8 (with embedded nulls).
=> test StaticString

include/json/value.h, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_valueiterator.inl, src/lib_json/json_writer.cpp, src/test_lib_json/main.cpp
Properly support UTF-8 by allowing embedded zeroes in strings.
fix #176.
=> allow zeroes in strings

include/json/reader.h, src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
https://sourceforge.net/p/jsoncpp/bugs/22/
Sekhar (shakers007) wrote:
> As per RFC4627 (section 2.2), names within an object should be unique. When using JSONCPP's strict mode, parsing such an object should fail.
As of now, JSONCPP does not return an error:
Sample JSON (duplicate_key.json):
```json
{
"Object": {
"Key":"Value",
"Key":"Value"}
}
```
Sample code to test the above file:
```cpp
ifstream inFile("duplicate_key.json");
Json::Value root;
Json::Reader reader(Json::Features::strictMode());
if ( false==reader.parse( inFile, root, false ) )
{
cerr << "Error reading file " << reader.getFormatedErrorMessages() << endl;
}
cout << root["Object"] << endl;
```
Output:
```json
{
"Key" : "Value"
}
```
=> Reject dup keys

include/json/assertions.h, include/json/value.h, include/json/writer.h, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_writer.cpp, src/test_lib_json/main.cpp
* Clarify when exceptions are thrown, to avoid crashes caused by malicious input.
* Use our own type (derived fro std::exception) so they are trappable.
=> Json::Exception

doxybuild.py
if str.split() without args, all empty string will drop
=> fix find_program() bug: no result in not-win sys

src/lib_json/json_writer.cpp
=> Fix snprintf

devtools/__init__.py, devtools/antglob.py, devtools/fixeol.py, devtools/tarball.py, makerelease.py, scons-tools/globtool.py, scons-tools/srcdist.py, scons-tools/substinfile.py, scons-tools/targz.py, test/cleantests.py, test/generate_expected.py, test/pyjsontestrunner.py, test/runjsontests.py, test/rununittests.py
This change adds explicit copyright information too python
files files.  The copyright year used in each case is the
date of the first git commit of each file.
The goal is to allow jsoncpp to be integrated into the
chromium source tree which requires license information in
each source file.
fixes #234
=> Add copyright information to .py files

src/lib_json/json_writer.cpp
We had already fixed Value to hold UTF-8 properly, but only the newer
StreamWriter was writing UTF-8 properly.
Old FastWriter etc. were using `asCString()` instead of `asString()` in
`Value::writeValue()`.
Hopefully this change does not break any existing code. Seems unlikely.
fix #240
=> support UTF-8 in old Writers

.travis.yml, dev.makefile, travis.sh
Because this runs apt-get, it will not work as-is for OSX. So when
we have OSX in Travis, we will have to wrap this somehow. See #250.
Closes #222.
=> run valgrind in Travis CI

README.md
This PR includes a small markdown fix for using the correct help option for `cmake` :)
=> [Documentation][Markdown] Use correct help option for cmake.

CMakeLists.txt, pkg-config/jsoncpp.pc.in
Do not prepend ${prefix} to substituted includedir & libdir
in the pkg-config file -- if the paths are overriden by user, CMake puts
absolute paths there (even if user specifies a relative path). Instead,
use the absolute path provided by CMake and appropriately default
LIBRARY_INSTALL_DIR & INCLUDE_INSTALL_DIR to absolute paths with
${CMAKE_INSTALL_PREFIX} prepended.
Fixes: https://github.com/open-source-parsers/jsoncpp/issues/279
=> Fix custom includedir & libdir substitution in pkg-config

src/lib_json/json_reader.cpp
=> fix ,/. problem in reader

CMakeLists.txt, src/lib_json/CMakeLists.txt
When compiling as a dependency for other applications it can be useful to keep the release & debug libraries in the same directory. This requires that the library names are different.
The patch adds a CMake option specify a suffix on the debug build and defaults to an empty string to match existing behaviour.
=> Allow an optional suffix on the debug library name in CMake

devtools/fixeol.py
`sys.stderr` is used in an `except` clause of `fix_source_eol()` but it will cause `NameError: name 'sys' is not defined` because the `sys` module is never imported.
=> Fix undefined name "sys"

appveyor.yml
* http://help.appveyor.com/discussions/problems/2229-v140-not-found-on-vs2105rc
```
Done Building Project "C:\projects\jsoncpp\jsoncpp.sln" (default targets) -- FAILED.
Build FAILED.
"C:\projects\jsoncpp\jsoncpp.sln" (default target) (1) ->
"C:\projects\jsoncpp\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\projects\jsoncpp\ZERO_CHECK.vcxproj" (default target) (3) ->
(PlatformPrepareForBuild target) ->
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then …
```
=> fix appveyor 32-bit windows build

CMakeLists.txt, src/lib_json/json_reader.cpp
I had to get the AppVeyor fix first, so I have rebased these commits.
=> fix warnings (-Wno-long-long and unused tokenStart)

.travis.yml
We will not actually set `-std=c++11` until v2, but we might turn it on for builds.
=> dockerize the Travis build, and allow C++11

.travis.yml
Travis CI APT is tricky. We cannot select a clang version if we select a gcc version. But the default clang (3.0) is good enough for now.
=> gcc-4.9, clang (3.0)

CMakeLists.txt
There was an issue with Travis, but we seem to be past that now.
We were using only `-std=c++0x` for gcc, as you can see in the diff.
=> -std=c++11 for gcc builds too

CMakeLists.txt
`-Werror` shouldn't be used in released code since it can cause random build failures on moderate warnings. It also depends on the used toolchain since different toolchains may or may not print the same warnings.
=> Remove -Werror

src/test_lib_json/main.cpp
Otherwise, on some 32 bit platforms this may not fit into long and compilation will fail:
src/test_lib_json/main.cpp:1260: error: integer constant is too large for 'long' type
=> Specify float constant as float

src/lib_json/json_writer.cpp
At all 3 places isMultiLine is checked in for loop :
for (int index = 0; index < size && !isMultiLine; ++index) {
It means !isMultiLine is always true (otherwise do not enter loop), so || condition does not depend on isMultiLine, so removed that.
=> Remove conditional check for isMultiLine

src/jsontestrunner/main.cpp
Catching exceptions thrown by parseCommandLine (std::bad_alloc & std::length_error) also.
=> parseCommandLine also throws

src/lib_json/json_reader.cpp
stackLimit default value is missing at two places.Adding them.
=> Add default value of stackLimit couple of places

src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
In addition to the C++ language version define __cplusplus also check _CPPLIB_VER for better Dinkumware support.
=> __cplusplus value should not be used to decide for std::unique_ptr #350:

src/lib_json/json_writer.cpp
Based on a patches to CMake by:
Ådne Hovda <ahovda@openit.com>:
commit 7b1cdb00279908cacabada92f8a53e4986465423
jsoncpp: Provide 'isfinite' implementation on older AIX and HP-UX
Newer AIX and HP-UX platforms provide 'isfinite' as a <math.h> macro.
Older versions do not, so add the definition if it is not provided.
Michael Scott <michael.scott@gbgplc.com>:
commit 9217b678b305d7df7471ba476a81bf28961fdfa3
jsoncpp: Provide 'isfinite' impl on more HP-UX versions (#15576)
Some versions of HP-UX do not define 'isfinite' or 'finite' in math.h
for Itanium when preprocessing with C++, so we have to add the
definition ourselves instead to map to the internal version.
Joerg Sonnenberger <joerg@bec.de>:
commit 75644dafe54c21902f14cfe58cb8338b553b69d8
jsoncpp: Fix compilation as C99 on Solaris
In C99 …
=> json_writer: improve isfinite support on *nix

src/lib_json/json_reader.cpp
Fix for issue #374: The defaulted default constructor has no effect, it would not initialize any bool member.
=> Remove defaulted default constructor

include/json/config.h, include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
* Add move constructor to Value::CZString
* Add unit test for Value move constructor
* Allow includer to specify in advance the value for
JSON_HAS_RVALUE_REFERENCES
rebased #264.
=> move ctors

CMakeLists.txt
Add an option JSONCPP_WITH_STRICT_ISO to disable compilation with `-pedantic` for GCC. If jsoncpp is build with the JSONCPP_WITH_WARNING_AS_ERROR option `-pedantic-errors` is used instead.
Commit 912d550 disabled `-Werror`. Enable it if jsoncpp is build with JSONCPP_WITH_WARNING_AS_ERROR=ON.
=> Disable -pedantic conditionally; add -pedantic-errors and -Werror conditionally

CMakeLists.txt
- if building as a submodule of another repository, installation of pkg-config files can fail because they may not be in the top-level binary directory
- this seems to happen because the CMake INSTALL command references ${CMAKE_BINARY_DIR}
- changing the INSTALL command to use ${CMAKE_CURRENT_BINARY_DIR} allows CMake to find the files for installation
=> Change ${CMAKE_BINARY_DIR} to ${CMAKE_CURRENT_BINARY_DIR}

CMakeLists.txt, include/json/config.h, include/json/reader.h, include/json/value.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_writer.cpp
See #411.
http://paste.debian.net/378673/
Wow. There are a lot of signed/unsigned oversights in this library. We should have turned on these compiler flags long ago. Hopefully, all the conversions are correct-by-construction (no underflow). LGTM. Comments?
=> Fix conversion warnings/errors

src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
Unfortunately MinGW32 (GCC 4.8.1-4) refuses to bulid jsoncpp. Giving the following error:
jsoncpp\src\lib_json\json_reader.cpp:33:18: error: 'snprintf' is not a member of 'std'
#define snprintf std::snprintf
This issue has been covered before (#231 and #244). Although this is most likely a bug in MinGW32, but as the project is inactive (and it is still shipped with the Windows build of QtCreator), I propose to add the following if clause here. If MinGW32 is detected std::snprintf is not used, but simply the old C library snprintf instead.
=> std::snprintf not part of std for MinGW32 using c++11

src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
Cygwin's current GCC (v4.9.3) has the same issue as described in #406. The fix described in the previous issue (using a preprocessor flag to skip the offending #define) works for this as well.
=> std::snprintf fix for Cygwin

src/lib_json/json_value.cpp
This patch removes two C-style casting, which causes warning then `-Wold-style-cast` is turned on in GCC.
=> remove C-style casting

src/lib_json/json_value.cpp
As per discussion in - https://github.com/open-source-parsers/jsoncpp/issues/404
Null should not be pass to memcmp, it may show undesired behaviour, so avoid doing that using assertion.
Also, changed one direct "assert" to JSON_ASSERT - it will be decided if exceptions are used or not.
=> Avoid passing Null to memcmp

include/json/config.h
This is PR for https://github.com/open-source-parsers/jsoncpp/issues/434
It will fix reported build error.
=> MinGW support while building as DLL

src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
This patch is also needed to build success for GCC 6.0.
Refer issue - https://github.com/open-source-parsers/jsoncpp/issues/411
=> Supporting GCC 6.0

include/json/value.h, src/lib_json/json_value.cpp
Resolve issue - https://github.com/open-source-parsers/jsoncpp/issues/389
=> NORETURN for throw functions in 0.x.y branch

include/json/config.h, include/json/reader.h, include/json/value.h, include/json/writer.h, src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp, src/test_lib_json/jsontest.h
b/c MS VS2010 is supposed to be C++11 but does not fulfull
the entire standard.
Resolves #410.
Re: #430.
=> Use macro for `override`

CMakeLists.txt
in 0.y.z branch -Werror was always being added regardless of the
what JSONCPP_WITH_WARNING_AS_ERROR was set to. Additionally,
-std=c++11 was being set on Clang builds.
=> Fix JSONCPP_WITH_WARNING_AS_ERROR

CMakeLists.txt
The current CMakeLists.txt can't be used with the Intel compiler, because it relies on setting the necessary -std=c++11 switch in a compiler detection block based on `CMAKE_CXX_COMPILER_ID`.
The Intel compiler accepts the same warnings options as gcc (see [here](https://software.intel.com/en-us/node/523320)--link for v.15 of the compiler which is less recent than the current v.16, but as far as I know nothing significant has changed here), so I have copied the same `-W` flags used for gcc.
The result compiles and builds correctly, although it gives a number of compatibility and portability warnings that I don't see when compiling with Apple Clang.
=> Add CMAKE_CXX_FLAGS for Intel compiler

include/json/config.h
This commit has been adapted from InsightSoftwareConsortium/ITK@1c86090
=> json/config.h: Generalize setting of JSONCPP_OVERRIDE to all compilers

CMakeLists.txt
This allows the jsoncppConfig file to keep working
when it is installed to a non-standard location
from a make DESTDIR=<location> install
=> By default use <prefix> relative paths when installing

src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp
=> Fix some warnings

include/json/config.h
On Visual Studio 2015 the macro `__cplusplus=199711L` (see http://rextester.com/CDCA6582), so the `override` keyword won't be used even though it is available. This adds an additional check to ensure the `override` keyword is used with recent versions of Visual Studio.
=> Use override keyword with Visual Studio.

include/json/value.h
use nvcc's preprocessor macro to make CZString class public
=> workaround for cuda 7.5 nvcc compiler

pkg-config/jsoncpp.pc.in
Recent commit 911e2b0fea ("By default use \<prefix\> relative paths when
installing") introduced relative install paths in CMake.  But this
interacts badly with commit e6f1cffdd3 from a year ago: now, the paths in
`pkgconfig/jsoncpp.pc` are relative, which is incorrect.
Before 911e2b0fea (1.7.2 on Archlinux), this was correct:
$ head -4 /usr/lib/pkgconfig/jsoncpp.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=/usr/include
After 911e2b0fea (1.7.3 on Archlinux), this is now incorrect:
$ head -4 /usr/lib/pkgconfig/jsoncpp.pc
prefix=/usr
exec_prefix=${prefix}
libdir=lib
includedir=include
This change causes hard-to-debug compilation errors for projects that
depend on jsoncpp, for instance:
CXXLD    libring.la
/tmp/ring-daemon/src/ring-daemon/src/../libtool: line 7486: cd: …
=> Fix compilation errors for downstream projects caused by incorrect pkconfig paths

src/lib_json/json_tool.h
On android, `struct lconv` is defined as an empty struct, so accessing `decimal_point` is a compiler error.
This PR adds a compile-time check, and `lc->decimal_point` is only compiled if we have a reason to believe it's there.
=> Workaround for missing lconv::decimal_point on android

src/lib_json/json_tool.h
Fixes issue #527. Some NDK platforms don't have locale support, so there should be a reliable way to disable the support for locales. Since it isn't possible to determine the current target platform, the best way to do this is using macros.
=> Used macros to disable localeconv() calls

CMakeLists.txt, src/lib_json/CMakeLists.txt
=> Add RPATH to dynamic library build on OSX

include/json/config.h
Otherwise failures like these one can happen during the configure phase
of other applications that use jsoncpp, like upmpdcli for instance:
checking jsoncpp/json/json.h usability... yes
checking jsoncpp/json/json.h presence... yes
checking for jsoncpp/json/json.h... yes
configure: error: libjsoncpp not found.
And this is the actual problem that you can see in config.log:
configure:5233: checking for jsoncpp/json/json.h
configure:5233: result: yes
configure:5259: /usr/bin/mipsel-linux-g++ -o conftest conftest.cpp
-lmicrohttpd -lmpdclient -lpthread  -ljsoncpp >&5
In file included from /usr/include/jsoncpp/json/autolink.h:9:0,
from /usr/include/jsoncpp/json/json.h:9,
from conftest.cpp:26:
/usr/include/jsoncpp/json/config.h:155:9: error: 'int64_t' does not name
a type
typedef int64_t Int64;
^ …
=> Include stdint.h necessary for int64_t and uint64_t

src/lib_json/json_value.cpp
Rename variable empty to emptyString in Value constructor to avoid shadowing of Value::empty().
GCC 4.8 produces the warning about this:
lib_json/json_value.cpp: In constructor ‘Json::Value::Value(Json::ValueType)’:
lib_json/json_value.cpp:346:27: warning: declaration of ‘empty’ shadows a member of 'this' [-Wshadow]
=> Rename variable empty to emptyString

src/lib_json/CMakeLists.txt, src/lib_json/json_tool.h
This should improve #527 by checking for locale support at configure time.
Example output from our Android build with this change:
```
-- Looking for C++ include clocale
-- Looking for C++ include clocale - found
-- Check size of lconv
-- Check size of lconv - done
-- Performing Test HAVE_DECIMAL_POINT
-- Performing Test HAVE_DECIMAL_POINT - Failed
-- Looking for localeconv
-- Looking for localeconv - not found
CMake Warning at third_party/jsoncpp/src/lib_json/CMakeLists.txt:25 (message):
Locale functionality is not supported
```
I would also like to suggest changing `NO_LOCALE_SUPPORT` to `JSONCPP_NO_LOCALE_SUPPORT` as to not clutter the global namespace. But this would break builds relying on `NO_LOCALE_SUPPORT`, so I didn't implement it.
=> Check for locale support in CMake

include/json/config.h, include/json/value.h, src/lib_json/json_value.cpp
throw() is deprecated in c++11. Should probably move to using noexcept instead
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3051.html
=> change throw() to noexcept to conform to c++11

include/json/allocator.h, include/json/features.h, include/json/reader.h, include/json/value.h, include/json/writer.h
Added pragma pack directive to jsoncpp headers.
Related to https://github.com/open-source-parsers/jsoncpp/issues/458
=> Add pragma pack directive

src/lib_json/json_reader.cpp
Removed a static variable used to contain the current recursion depth of Reader::readValue().  The number of elements in an internal container Reader::nodes_  is used instead.  It is correct because any recursive call of Reader::readValue() is executed with adjacent nodes_.push()  and nodes_.pop() calls.  
Added the option to change the allowed recursion depth at compile time by defining a macro JSONCPP_DEPRECATED_STACK_LIMIT as the required integer value.
=> Removed a static variable used to contain the current recursion depth in json_reader.cpp

src/lib_json/json_value.cpp
=> std::min<unsigned>, for VS2015

pkg-config/jsoncpp.pc.in
Using full paths is more versatile. The current solution
breaks when specifying an absolute path for `CMAKE_INSTALL_INCLUDEDIR`
which is an otherwise supported option by CMake's `GNUInstallDirs`.
=> Use full CMake paths in pkg-config template

src/lib_json/json_value.cpp
Null value in Value constructor will crash strlen(). Avoid crash with JSON_ASSERT_MESSAGE
=> Fix crash issue due to NULL value.

src/lib_json/json_value.cpp
Worst case (f.e. realValue = 1.5) calls modf() once. Was twice.
=> Optimize Value::isIntegral() method

include/json/config.h, src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
Previously, the code tried to avoid a `-Wdeprecated-declarations` warning by avoiding `std::auto_ptr` (since #413). However, the implementation has two issues:
1. It uses `std::scoped_ptr`, which as far as I can tell is a nonexistent type. `std::unique_ptr` is presumably what was meant.
2. It avoids `auto_ptr` whenver we're using GCC6. This means we don't dodge warnings for GCC5 or clang (which also support C++11). It also means that using GCC6 in C++03 mode fails, because `std::unique_ptr` doesn't exist there.
This fixes both of these issues, using `std::unique_ptr` in C++11 (and MSVC2010) and above.
Tested on GCC 5.4.1, GCC 6.2.0 and Clang 5.0.0-svn300863 in both C++03 and C++11 modes.
=> Use std::unique_ptr correctly across compiler and language versions

AUTHORS, LICENSE, devtools/__init__.py, devtools/antglob.py, devtools/fixeol.py, devtools/licenseupdater.py, devtools/tarball.py, makerelease.py, scons-tools/globtool.py, scons-tools/srcdist.py, scons-tools/substinfile.py, scons-tools/targz.py, test/cleantests.py, test/generate_expected.py, test/pyjsontestrunner.py, test/runjsontests.py, test/rununittests.py
Google advises its employees to add Google Inc. as an author, but that hasn't
been done yet and would be super inconvenient. So instead I've refactored the
file to refer to "The JsonCpp Authors", which are listed in the AUTHORS file.
The AUTHORS file itself is generated via:
git log --pretty="%an <%ae>%n%cn <%ce>" | sort | uniq
Plus the addition of "Google Inc." as a copyright author. (Google owns the work
of anyone contributing from an @google.com address, for example.)
The list contains some probable duplicates where people have used more than one
email address. I didn't deduplicate because -- well, who's to say they're
duplicates, anyway? :)
=> Refactor authorship information for more technical accuracy.

src/lib_json/json_writer.cpp
Use snprintf instead which is already used in this file. Also, using snprintf is safer than sprintf.
=> Fix QNX build: QNX defines sprintf under the std namespace. 

src/lib_json/json_writer.cpp
Warning:
```
/root/firefox-gcc-last/toolkit/components/jsoncpp/src/lib_json/json_writer.cpp:139:16: note: using the range [-2147483648, 2147483647] for directive argument
/root/firefox-gcc-last/toolkit/components/jsoncpp/src/lib_json/json_writer.cpp:146:10: note: 'sprintf' output between 5 and 15 bytes into a destination of size 6
sprintf(formatString, "%%.%dg", precision);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Allocate the proper memory for formatString. Fix a warning with gcc 7.1

src/lib_json/json_writer.cpp
The output of snprintf might produce ',' separators for decimal places if
certain locales are set. This commit moves the converversion from ',' to '.'
at the correct place. Otherwise an additional ".0" might be appended.
=> Fix issue #567 in writing real values in different locales

include/json/value.h, src/lib_json/json_value.cpp
TODO: add move assignment for CZString class also.
One problem is that I had to change the copy assignment from pass by value to pass by const reference because json_reader was giving errors of ambiguous overloads.
Though to make all tests pass I had to do a const_cast inside the assignment operator since I couldn't do a copy but rather a swap.
I don't like that and would like to fix this. But why is the swap necessary ? shouldn't it be a copy ?
=> Add move assignment operator for Json::Value class and overload append member function for RValue references

appveyor.yml, src/lib_json/CMakeLists.txt
When both static and shared lib build are enabled, there is a conflict between the static and import lib ; both are named jsoncpp.lib and the test was incorrectly linked to the static lib but built with JSON_DLL flag and so failed to import symbols with the dllimport keyword. We propose to fix this by appending a "_static" suffix to the static lib when the shared lib is also enabled, so as by default (shared=0, static=1) the behavior is still the same.
This fixes #631.
Also, the appveyor script was messy and mixed msvc versions and 32/64 bits configurations.
=> Fix shared/static lib build conflict

include/json/value.h, src/lib_json/json_value.cpp
Pull request #635 has changed the behavior of non-rvalue assignment operator from copying the 'other' value to swapping with it. There is a lot of wrong with it.
This pull request reverts to the earlier assignment operator, with 'other' passed by value rather than const&. Now that Json::Value has a move constructor, such assignment operator covers both move and non-move cases.
=> Fix non-rvalue Json::Value assignment operator (should copy, not move)

src/lib_json/json_reader.cpp
But simply use `.assign()` instead of the extra copy. (See comment from @BillyDonhue at #580.)
See #578. Thanks @ya1gaurav and @cinemast.
(@SoapGentoo, thanks for the Meson stuff. Beautiful!)
=> Avoid memory error

README.md, meson.build
Fix for compile issue when compile there were error in `config.h` and `value.h` in pre-processing code, details in issue #659.
=> Hotfix for compile issue #659

include/json/value.h
Without value_type, Boost.Test version 1.65.0 throws a compiler error when a Json::Value object is compared to another with BOOST_TEST. Example and further discussion are in https://github.com/open-source-parsers/jsoncpp/issues/671.
=> Add value_type to improve integration with boost

meson.build
Fix meson.build so that jsoncpp can be used as a meson subproject, potentially wrapped.
Previously the declared dependency object has no name and cannot be retrived var `get_variable()` from the parent project and cannot be used directly, which also prevents jsonspp to be used as a fallback subproject in `dependency()`.
=> Fix meson.build to allow using jsoncpp as a subproject

src/lib_json/json_writer.cpp
Handling Unicode charactes, assuming strings are UTF-8
=> Serialize UTF-8 string with Unicode escapes

include/json/value.h, src/lib_json/json_value.cpp
Sometimes we just want to remove something we don't need anymore. Having
to supply a return buffer for the removeMember function to return something
we don't care about is a nuisance. There are removeMember overloads that
don't need a return buffer but they are deprecated. This commit un-deprecates
these overloads and modifies them to return nothing (void) instead of the
object that was removed.
Further discussion: https://github.com/open-source-parsers/jsoncpp/pull/689
WARNING: Changes the return type of the formerly deprecated removeMember
overloads from Value to void. May break existing client code.
=> Un-deprecate removeMember overloads, return void

README.md
By default, ninja / meson install to /usr/local or the system equivalent. Some users (such as myself) work in complex environments where it is impossible or undesirable to install to such a location. While it didn't take much work for me to find out how to do this, it is beneficial to explicitly state it in the installation instructions.
=> Add comment to README with instructions on installing to a specific path

src/jsontestrunner/main.cpp, src/test_lib_json/main.cpp
- only use "#pragma GCC" on GCC-compatible compilers
- suppress deprecation warnings also on MSVC
=> MSVC warning fixes in tests

src/lib_json/json_reader.cpp
GCC 7, when compiling with -Wimplicit-fallthrough=1 or higher, issues a warning which can be suppressed using a comment that matches certain regular expressions. The comment change does just that: signal to GCC that the fall through is intentional.
Fixes #676
=> Suppress implicit-fallthrough warnings from GCC 7

src/lib_json/json_writer.cpp
`valueToString` takes an argument `unsigned int precision`, but it is used with `%d` rather than `%u` in the `snprintf` format string. Make the format string look for an unsigned value instead.
=> Fix sign mismatch in `valueToString`

include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
In a boolean context, a Value is `false` if it is null, and `true` if it is not null. This was already implemented partially by `operator!` and is now supported fully by adding implicit conversion of Value to bool (through `operator bool`).
For example:
```cpp
Json::Value v;
...
// We already had this before (through operator!):
if (!v) {
// Executed if v is null
}
// This commit adds the following (through the new operator bool):
if (v) {
// Executed if v is not null
}
```
Includes test coverage.
=> Allow Json::Value to be used in a boolean context

.travis.yml
```
Unfortunately, since our latest image update, Python 3.5 doesn't come pre-installed anymore. Hence, you will have to install it via `pyenv` as a first step e.g.
before_install
- pyenv install 3.5.0 && pyenv global 3.5.0
support@travis-ci.com
```
=> pyenv install

meson.build
We set this is the Meson build to eliminate warnings, but
c++0x should still work, at least for now.
See #695 for discussion.
=> -std=c++11

.travis.yml
Even though TravisCI says Trusty has ["2.7.6 and 3.4.3"](https://docs.travis-ci.com/user/languages/python/), python-3.4.3 is missing pip3. TravisCI reports:
The `pip3` command exists in these Python versions: 3.6, 3.6.3
We recently had to start using the very slow `pyenv install` for some other version of Python. But fortunately, 3.6 actually is available to pyenv now. So we save 3 minutes of build-time. (Actually, we just go back to the build-time we had last week, before TravisCI made some updates.)
=> Speed up TravisCI build

include/json/reader.h
Should fix #728.
This has been only tested locally running VS2017.
=> Fix C4996 warning with VS2017 by postponing the deprecation of Reader

src/lib_json/json_value.cpp
Hi guys,
There're two commits here. 
The first one could be considered to be a minor bug fix (_std::move_).
The second one is disputable. It slightly changes _Value::removeMember_ interface, so it could take _nullptr_ as the "removed" argument. It seems to be a pretty common use case since that extra returned value is not needed for everyone. Also, changing tons of code to support the new _removeMember_ interface could be much easier with this nullptr-feature.
Regards
=> Move the existing value to "removed" argument; removed is optional (could be nullptr)

src/lib_json/json_writer.cpp
During review of my own JSON string escaping code against popular implementations, I noticed an inaccuracy in yours. Codepoints for 4-byte long utf-8 characters are calculated incorrectly:
```
unsigned int calculated = ((firstByte & 0x07) << 24)
| ((static_cast<unsigned int>(s[1]) & 0x3F) << 12)
| ((static_cast<unsigned int>(s[2]) & 0x3F) << 6)
|  (static_cast<unsigned int>(s[3]) & 0x3F);
```
Notice the byte shift of 24, while there are just 3x6 bits stored in bytes with lower significance.
=> Incorrect byte shift when interpreting 32-bit utf-8 codepoints

include/json/value.h
Comply with the [Swappable](http://en.cppreference.com/w/cpp/concept/Swappable) concept without opening namespace std.
=> Remove std::swap<Json::Value> in favor of ADL

include/json/value.h, include/json/writer.h, src/lib_json/json_tool.h, src/lib_json/json_value.cpp, src/lib_json/json_writer.cpp, src/test_lib_json/main.cpp
In thread of issue https://github.com/open-source-parsers/jsoncpp/pull/648 was an idea to make precision settable. So, this PR do that and also add decimal places precision setting.
=> Add setting precision for json writers and also add decimal places precision type.

CMakeLists.txt
It seems like the right thing to do here is to always provide the CMake Config files, unless they are undesirable for some reason. This makes it more likely that people will use the provided CMake Config files as opposed to rolling their own `FindJsonCpp.cmake` script because they don't know the library can provide it.
=> [CMake] Generate CMake config files by default

src/lib_json/json_writer.cpp, src/test_lib_json/main.cpp
=> Fix msvc /fp:fast test failure

src/lib_json/json_value.cpp
I want to fix the issue: #759.
Jsoncpp project will generate many warnings in vs2017. In my environment, all of the warnings are C4702: unreachable code.
Add few lines to suppress this warning.
Tested in local environment, compiling jsoncpp lib in vs2017 and no warning is  generated.
=> Disable warning "C4702" when compiling json cpp using vs2013 and above

src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
refactoring cross compiler macro
If compiler is c++11 compliant, use std version.
=> refactoring cross compiler macro

src/lib_json/json_tool.h, src/lib_json/json_writer.cpp
Use iterators to deal with string fixups. smarter use of precision in writing.
Inspired by PR #772
=> Improvements in writing precision and json_tool.h helpers.

include/json/value.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_writer.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/jsontest.h
Cppcheck version - 1.83
There are still lots of non-explicit constructors.
=> Multiple fixes for issues found by Cppcheck

README.md, meson.build, travis.sh
Add preprocessor definitions for MSVC dllexport/dllimport statements
(cherry picked from commit 2654b6bbbf089bf85d29c9a9ca1283e07cc6fe43)
=> Fix for #798

.travis.yml, travis.before_install.linux.sh, travis.before_install.osx.sh, travis.install.linux.sh, travis.install.osx.sh, travis.sh
=> in travis, build for osx also

src/test_lib_json/main.cpp
Finds and replaces integer literals which are cast to bool.
SRCDIR=/Users/johnsonhj/src/jsoncpp #My local SRC
BLDDIR=/Users/johnsonhj/src/jsoncpp/cmake-build-debug/ #My local BLD
cd /Users/johnsonhj/src/jsoncpp/cmake-build-debug/
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-use-bool-literals  -header-filter=.* -fix
=> STYLE: Replace integer literals which are cast to bool.

include/json/value.h
#693 has changed `removeMember` but did not update the docs.
=> Update removeMember docs after #693

src/lib_json/json_writer.cpp
```c++
#include <iostream>
class TestBool
{
public:
TestBool():addChildValues_(){}
TestBool(int):addChildValues_(false){}
bool addChildValues_ : 1;
bool indented_ : 1;
};
int main()
{
std::cout << "\n TestBool () addChildValues_ = " << TestBool().addChildValues_;
std::cout << "\n TestBool false addChildValues_ = " << TestBool(3).addChildValues_;
return 0;
}
```
```text
root@osssvr-1 # /opt/SUNWspro/prod/bin/CC  testbool.cpp -o testbool   
Error: Cannot take the address of a bit field.
1 Error(s) detected.
```
=> fiexd “Cannot take the address of a bit field.”

src/lib_json/json_reader.cpp
Clang's ubsan (-fsanitize=undefined) reports:
runtime error: negation of -9223372036854775808 cannot be represented in
type 'Json::Value::LargestInt' (aka 'long'); cast to an unsigned type to
negate this value to itself
Follow its advice and update the code to remove the explicit negation.
=> reader: fix signed overflow when parsing negative value

include/json/features.h, include/json/reader.h, include/json/value.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_valueiterator.inl, src/lib_json/json_writer.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/jsontest.h, src/test_lib_json/main.cpp
Run clang-tidy code modernization refactoring tools.  The set of scripts used for this repository have been in heavy use on many large repositories that are moving to C++11 support.
cd /Users/johnsonhj/src/jsoncpp/cmake-build-debug/
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-pass-by-value  -header-filter=.* -fix
=> STYLE: Use modern C++11 style

include/json/assertions.h, include/json/config.h, include/json/features.h, include/json/reader.h, include/json/value.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/lib_json/json_valueiterator.inl, src/lib_json/json_writer.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/jsontest.h, src/test_lib_json/main.cpp
```
$ clang-format -i -style=file \
$(find  . | egrep '.*\.(h|cpp|inl)$')
```
Also did some manual commenting to keep test data lines from joining up,
since they rely on `__LINE__` to be meaningful.
=> Reapply clang-format.

.clang-format, include/json/config.h, include/json/features.h, include/json/value.h, include/json/writer.h, src/jsontestrunner/main.cpp, src/lib_json/json_writer.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/jsontest.h, src/test_lib_json/main.cpp
Made changes to .clang-format necessary to support C++11, then applied them.
If we don't set clang-format to `Standard: Cpp11`, it will generate incorrect code sometimes.
In particular, it will misinterpret and break C++11's new raw string literals.
=> C++11 clang format

amalgamate.py, include/json/value.h, src/lib_json/json_value.cpp
This allows special functions to be implemented more easily.  #873
=> pack the {type,allocated} bitfield

include/json/config.h
clang-cl defines `_MSC_VER` by default, so `JSONCPP_DEPRECATED` was first
defined for MSVC and then redefined for clang. Integrate the MSVC
definition into the block with clang and GCC's `JSONCPP_DEPRECATED`
definitions to fix this.
=> Fix macro redefinition warning with clang-cl

include/json/value.h, src/lib_json/json_value.cpp
Preserve the lazy-init semantics, so comments_ only adds 1 pointer to a Value if it's not used.
Switch to `std::unique_ptr` and `std::array` now that we're in C++11.
Use `Json::String` instead of `const char*` with manually-specified special `releaseStringValue` etc stuff.
=> refactor comments_ into a copyable class

CMakeLists.txt, include/json/value.h, meson.build, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
There's a declaration of a `Value::demand()` method, but an implementation is nowhere to be found.
It would have some utility, though: it's the only method to create a named key that takes `[begin, end)` arguments. This is useful if you want to use a key stored in a `string_view`.
Note that I also changed the return value of `demand()`:
* I think a non-const pointer is more useful as you can immediately modify the `Value`.
* Leaving it as a pointer keeps some symmetry with `find()`.
* This change doesn't affect compatibility much, as `demand()` wasn't implemented, thus there can't be any user of it.
=> Implement Value::demand()

include/json/config.h
This allows building into a shared lib with `-fvisibility=hidden` specified.
=> Explicitly set JSON_API to 'default' visibility on clang & gcc

include/json/value.h, src/lib_json/json_value.cpp
This patch fixes the JSON_USE_EXCEPTION flag. Currently, due to the
throwRuntimeError and throwLogicError methods implemented in json_value,
even if JSON_USE_EXCEPTION is set to 0 jsoncpp will still throw. This
breaks integration into projects with -fno-exceptions set, such as
Chromium.
=> Fix JSON_USE_EXCEPTION=0 use case

include/json/forwards.h
=> Add missing classes to forwards.h

meson.build
Currently, we have a build type warning due to listing a requirement for
meson build version that doesn't implement features we use in our build
file. The minimum meson build version required is actually 0.50.0, so
this PR updates our meson.build file to depend on 0.50.0.
=> Update meson build requirement

include/json/config.h, include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
Clang format hasn't been run on some recent checkins. This patch updates
the repository with clang format properly run on all files.
=> Run clang format

CMakeLists.txt
For proper cmake configuration setup, one should also deliver some config-version file. This allows consumers to check for some minimal/required version when importing.
The version compatibility was arbitrarily set to SameMajorVersion, SameMinorVersion or ExactVersion should probably be some smarter choice.
Please let me know if any change is required.
=> added cmake config version file for proper cmake delivery

.travis.yml, .travis_scripts/cmake_builder.sh, .travis_scripts/travis.before_install.linux.sh, .travis_scripts/travis.before_install.osx.sh, .travis_scripts/travis.install.linux.sh, .travis_scripts/travis.install.osx.sh, appveyor.yml
This PR updates the Travis and Appveyor configs to use more recent
toolchain versions, allowing for better C++11 compliance.
=> Modernize Travis and Appveyor configs

src/test_lib_json/main.cpp
Testing shows no problems on the jsoncpp side.
=> Add WideString test for Issue #756

src/lib_json/json_reader.cpp
This patch removes an unchecked conversion from a 64bit wide type
to a 32bit wide type, fixing a compile error on some platforms.
Issue #920
=> Issue 920: Fix android build with casting fix

src/lib_json/json_reader.cpp
As the issue #812 mentioned before, I'm sure there are some typo error in the `Reader::pushError()` funtion,
there should be a consisency with other functions like :
```c++
620 bool Reader::decodeString(Token& token) { 
621   String decoded_string; 
622   if (!decodeString(token, decoded_string)) 
623     return false; 
624   Value decoded(decoded_string); 
625   currentValue().swapPayload(decoded); 
626   currentValue().setOffsetStart(token.start_ - begin_); 
627   currentValue().setOffsetLimit(token.end_ - begin_); 
628   return true; 
629 } 
```
=> repair a typo error

src/lib_json/json_value.cpp
According to JavaScript language, `0.0` and `NaN` are treated as `false`, others are treated as `true`. See 
[JavaScript Booleans](https://www.w3schools.com/js/js_booleans.asp).
C++11 has already provided a function `fpclassify` to test a real number is zero or NaN. See [std::fpclassify](https://en.cppreference.com/w/cpp/numeric/math/fpclassify), so the unsafe comparison from `0.0f` should change to using this function.
=> Use fpclassify to convert real number to bool

src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
We currently don't have any checks for clang formatting as part of our
check-in process, this is an incremental patch to get things compliant.
=> Run clang-format on the repository

src/lib_json/json_reader.cpp
There have been multiple discussions of the inaccurate comments in the
Json Reader class. This patch just updates those comments.
Note: this PR partially fixes #619
=> Fix comments on Json Reader

src/lib_json/json_reader.cpp
We should pop the root node after readValue, although there is no problem when we don't care it, because it's the node at the bottom of the stack,  but in order to maintain consistency, it's better to pop it out.
=> pop the root node after readValue()

include/json/value.h, src/lib_json/json_value.cpp
This patch removes the custom JSONCPP_NORETURN macro in favor of the
C++11 standard [[noreturn]] attribute.
#964
=> #964 Delete JSONCPP_NORETURN for [[noreturn]]

include/json/config.h, include/json/value.h, src/lib_json/json_value.cpp
This patch adds a new flag, JSON_USE_NULLREF, which removes
the legacy singletons null, nullRef for consumers that require not
having static initialized globals, like Chromium.
=> Add new JSON_USE_NULLREF flag

include/json/reader.h
This patch fixes issue #979, where the parseFromStream definition in
the header is different from the implementation.
=> #979 Fix parseFromStream definition

include/json/value.h, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp
=> [Language Conformance] Use constexpr restriction in jsoncpp

src/lib_json/json_value.cpp
Currently, a Segmentation fault (core dumped) caused by the wrong use of setComment method:
```c++
root.setComment(commentPtr, Json::numberOfCommentPlacement);
```
we should check the comment array boundry before we assign comment value to Array to avoid this seg fault.
=> Check the comments array boundry.

include/json/writer.h
Add missing file write.h in issue #985
=> Modify code comments in write.h

src/lib_json/json_reader.cpp
(This is basically PR #1001 plus some change suggestion from it's discussion.)
Currently when failIfExtra is set and strictRoot is not set,
OurReader::parse() will accept trailing non-whitespace after the JSON value
as long as the first token is not a valid JSON token. This commit changes
this to disallow any non-whitespace after the JSON value.
This commit also suppresses the "Extra non-whitespace after JSON value."
error message if parsing was aborted after another error.
=> Do not allow tokenError tokens after input if failIfExtra is set.

src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
Add case "+" in readToken to allow it to read explicit positive number token.
=> Reinforce readToken function

include/json/config.h
The current check to define JSON_USE_INT64_DOUBLE_CONVERSION
works for GCC but not clang.
Clang does define __GNUC__ but with a value 4 which misses
the check for >= 6.
This avoids the -Wimplicit-int-float-conversion warning
when jsoncpp is built with a recent version of clang.
Signed-off-by: Manoj Gupta <manojgupta@google.com>
=> jsoncpp: Define JSON_USE_INT64_DOUBLE_CONVERSION for clang as well.

src/lib_json/json_value.cpp
This patch fixes an implicit long to double conversion, fixing
compilation on the as-of-yet unreleased clang v10.
#1021
=> Issue #1021: Fix clang 10 compilation

src/test_lib_json/main.cpp
The value of CopyObject has the following scenarios: object, array, string. The object is missing.
=> add a testcase in ValueTest:CopyObject

pkg-config/jsoncpp.pc.in
exec_ and prefix must be overridden  in such a case.
Makes the .pc file more consistent with other projects.
=> pkgconfig: Fix for cross compilation

include/json/config.h, include/json/reader.h, include/json/value.h, include/json/writer.h
[[deprecated]] is a C++14 extension, and was mistakenly introducted into the code base.
This patch removes it from JsonCpp.
=> Issue #990: Remove unsupported C++14 features

src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/main.cpp
Fix the clang-format errors, which are reported from #1026 's Trivis CI
=> fix clang-format error for ci

include/json/value.h, src/lib_json/json_value.cpp
Restores Visual Studio 2013 compatibility.
=> Re-add JSONCPP_NORETURN replacing [[noreturn]]

src/test_lib_json/main.cpp
After add these testcases, the line coverage of the file `json_writer.cpp` can be increased to 75%.
Before:
After:
Related issue: #1038
=> add testcases for writerTest [improve coverage]

example/readFromString/readFromString.cpp, src/lib_json/json_value.cpp, src/test_lib_json/fuzz.cpp
Currently the fuzzer has an off by one error, as it passing a bad length
to the CharReader::parse method, resulting in a heap buffer overflow.
=> Fix fuzzer off by one error

include/json/value.h, src/lib_json/json_valueiterator.inl
The protected deref method had inconsistent interface
of being a const function that returned a non-const
reference.  Resolves #914.
=> COMP: Improve const correctness for ValueIterators

README.md, src/test_lib_json/main.cpp
change int to Json::ArrayIndex in for-loop
=> update coverage badge and change int to Json::ArrayIndex in for-loop

include/json/value.h, src/test_lib_json/main.cpp
Julian I took out the macros and tried to compress the unit tests a bit.
It's just a suggestion. You can take it or leave it, really.
=> Issue 1066

src/test_lib_json/main.cpp
update charReader test case
Coverage of json_reader.cpp raises up to 89.52%
=> update charReader test case

src/test_lib_json/main.cpp
refactor test 'CharReaderAllowDropNullTest/issue178' and others
=> eliminate some redundancy in test_lib_json/main.cpp

include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
According to the conclusion in issue #1046, the `insert` should follow the standard container members like vector::push_back, which will always have a const T& and a T&& overload. 
This patch is to fix this problem.
=> Add insert overload method

src/test_lib_json/main.cpp
Add test cases for Reader in src\lib_json\json_reader.cpp.
=> Add test cases for Reader 

CMakeLists.txt
Allows to conditionally build examples as it has been done for tests.
Useful for packaging.
=> Add option JSONCPP_WITH_EXAMPLE

src/test_lib_json/main.cpp
1.From https://github.com/open-source-parsers/jsoncpp/pull/1095#discussion_r345037318, this PR will replace raw unicode.
2.Fix the wrong use of JSONTEST_ASSERT_EQUAL, the expected value is the first.
=> Replace Raw Unicode in Testcase

src/lib_json/json_writer.cpp
This bug is only affects platforms where `char` is unsigned.
When char is a signed type, values >= 0x80 are also considered < 0,
and hence require escaping due to the < ' ' condition.
When char is an unsigned type, values >= 0x80 match none of the
conditions and are considered safe to emit without escaping.
This shows up as a test failure:
* Detail of EscapeSequenceTest/writeEscapeSequence test failure:
/build/source/src/test_lib_json/main.cpp(3370): expected == result
Expected: '["\"","\\","\b","\f","\n","\r","\t","\u0278","\ud852\udf62"]
'
Actual  : '["\"","\\","\b","\f","\n","\r","\t","ɸ","𤭢"]
'
=> json_writer: fix inverted sense in isAnyCharRequiredQuoting

CMakeLists.txt, include/json/version.h, meson.build, meson_options.txt
Hi Chris,
we'd like to disable tests for most users in Gentoo, hence I've made them optional (but still default enabled). I've modernised some parts of the `meson.build` too.
=> Meson updates

.clang-tidy, src/jsontestrunner/main.cpp, src/lib_json/json_reader.cpp, src/lib_json/json_value.cpp, src/test_lib_json/fuzz.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/main.cpp
I ran it through CMake this time. Coverage is greater.
=> clang-tidy fixes again

CMakeLists.txt, example/CMakeLists.txt, src/jsontestrunner/CMakeLists.txt, src/lib_json/CMakeLists.txt, src/test_lib_json/CMakeLists.txt
The ccache must be setup before call project() at CMakeLists.txt
cmakelint all cmake files
This fix https://github.com/open-source-parsers/jsoncpp/issues/1138 too
=> Use ccache right

include/json/value.h
For Apple clang-800.0.42.1, which was released with Xcode 8 in September 2016, the '=delete' on the 'is' and 'as' methods introduced in 53c8e2cb causes the following errors for value.h:
inline declaration of 'as<bool>' follows non-inline definition
inline declaration of 'is<bool>' follows non-inline definition
etcetera for the other specializations of 'is' and 'as'.
I understand, of course, that this use of '=delete' serves a purpose: it allows the C++ compiler to detect when a program uses specializations of `is()` and `as()` that aren't implemented.  However, this patch will be useful (necessary, in fact) for people who build their projects with Xcode 8.
=> Remove '=delete' from template methods for Xcode 8

include/json/json_features.h, src/lib_json/json_reader.cpp
According to https://github.com/open-source-parsers/jsoncpp/pull/1062#issuecomment-549530234 and https://github.com/open-source-parsers/jsoncpp/pull/1098#issuecomment-554256725, this PR will revert the changes to the old Reader.
=> revert trailing comma in old Reader

amalgamate.py
Required to get JSONCPP_USING_SECURE_MEMORY available.
=> amalgamate: add version.h to the forwards header

CONTRIBUTING.md, meson.build, test/runjsontests.py
A recent PR broken the JsonChecker tests by adding support for trailing
commas. This didn't end up breaking the build, because those tests
aren't run, except locally and only using CMake.
This patch fixes the tests by adding exclusions for trailing comma
tests, as well as updates Meson to run these tests as part of `ninja
test`.
See issue #1102.
=> Issue 1102: Fixup test suite, fix broken tests

src/lib_json/json_value.cpp
Tested: used this to debug an issue in my code.
=> Make `throw.*Error` print `msg` when built with JSON_USE_EXCEPTION=0

src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
=> Ignore byte order mark in the head of UTF-8 text.

src/lib_json/json_reader.cpp, src/test_lib_json/main.cpp
Modify condition and the optional name.
=> allowBom -> skipBom

CMakeLists.txt, src/test_lib_json/CMakeLists.txt
Fix https://github.com/open-source-parsers/jsoncpp/issues/1163
=> Put ".exe" and ".dll" together to make test usable in build dir.

README.md
The `./` is needed before `vcpkg install jsoncpp` when installing with PowerShell.
=> Added current dir specifier for PowerShell

include/json/value.h
Anonymous struct is introduced in C++11, and some old compilers may compile error.
=> fix compile error : anonymous struct

src/lib_json/json_writer.cpp, src/test_lib_json/main.cpp
=> Escape control chars even if emitting UTF8

src/lib_json/json_reader.cpp, test/data/fail_invalid_quote.json
This patch fixes a fuzzing bug by resolving a bad fallthrough in the
setComment logic.
The result is that we get a proper error instead of an assert, making
the library friendlier to use and less likely to cause issue for
consumers.
See related Chromium project bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=989851
Issue: 1182
=> Issue 1182: Fix fuzzing bug

src/lib_json/json_writer.cpp
`std::isprint` is locale-specific and the JSON-spec is not.
In particular, isprint('\t') is true in Windows CP1252.
Has bitten others, e.g. https://github.com/laurikari/tre/issues/64
Fixes #1187
=> avoid isprint, because it is locale specific

src/test_lib_json/main.cpp
Unit test contribution for https://github.com/open-source-parsers/jsoncpp/pull/1189
=> Windows tab encoding with custom locale test

include/json/value.h
I found some unexpected behavior when using this library when comparing a `Json::Value` to `nullptr`. This was my sample program:
```c++
#include <jsoncpp/json/json.h>
#include <iostream>
int main()
{
Json::Value test("Hello world!");
Json::Value test2(Json::nullValue);
if (test == nullptr)
{
std::cout << "test is null" << std::endl;
}
if (test2 == nullptr)
{
std::cout << "test2 is null" << std::endl;
}
return 0;
}
```
Since before this change, `Json::Value` objects can be compared with other `Json::Value` objects, a implicit `Json::Value` object will be constructed with `nullptr` as it's parameters. Given the only valid constructor for `nullptr` was the `const char *`, the program aborts with the following output:
```
terminate called after throwing an instance of 'Json::LogicError' …
```
=> Add nullptr Json::Value constructor

.travis_scripts/cmake_builder.sh, CMakeLists.txt, src/jsontestrunner/CMakeLists.txt, src/lib_json/CMakeLists.txt, src/test_lib_json/CMakeLists.txt
User @AMDmi3 put forward a requirement in issue #1170 , that is to use cmake to compile both static and shared libraries. After some investigation, I found that this is a very practical usage scenario. At the same time, I also know a common software usage scenario: In a large software system, the JSON parsing library(like JsonCpp) is the basic library of the system. Client may only need the `xxx.o` files of these basic libraries, and then link them into a shared library(`yyy.so` file) to use. Therefore, I made this patch.
During this time, I noticed the PR #827, I think the names of static libraries and dynamic libraries should be different. When users call them externally, they should be very clear about what type of libraries they are using, and a different names can guarantee this.
So, …
=> Enhance cmake script

.gitignore, CMakeLists.txt, cmake/JoinPaths.cmake, pkg-config/jsoncpp.pc.in
The CMake variables `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` are not guaranteed to be relative paths. If they are absolute, an invalid pkg-config file is generated.
See https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files for more information.
=> Fix generation of pkg-config file with absolute includedir/libdir.

meson.build
Not all distributions provide Python as python3 and as Meson already depends on 3.5+ just use what Meson uses.
References: https://mesonbuild.com/Getting-meson.html
https://mesonbuild.com/Python-module.html#find_installation
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
=> meson: Don't specifically look for python3

include/json/allocator.h
This fixes the following issue:
https://github.com/open-source-parsers/jsoncpp/issues/1193
=> Fix c++20 compilation problem for clang10

include/json/value.h
Disable Visual Studio warning C4275 (std::exception used as base…class in dll-interface class) together with C4251, when building as DLL and JSONCPP_DISABLE_DLL_INTERFACE_WARNING is defined.
This PR relates as well to issue https://github.com/open-source-parsers/jsoncpp/issues/730
=> Fix Visual Studio warning C4275

src/lib_json/CMakeLists.txt
solves issue #1245, has been tested with visual studio 2019, mingw-w64 on msys2, and Linux
=> only append _static suffix for microsoft toolchains

src/test_lib_json/main.cpp
Use ArrayIndex instead of int.  Fixes #1266
=> fix sign-conversion warning

src/lib_json/json_value.cpp
Avoid allocation if the set is going to be rejected anyway.
Prototype suggestion from #1277 review thread
=> Rearrange Comments::set

CMakeLists.txt
conversion & sign-compare errors should be enabled only if `JSONCPP_WITH_WARNING_AS_ERROR` is enabled also.
=> CMake: conversion & sign-compare errors only if warnings as errors enabled

BUILD.bazel
Adds support for using JsonCpp as an external package in [Bazel](https://www.bazel.build/) projects.
Tested in https://github.com/google/verible by replacing:
```
http_archive(
name = "jsoncpp_git",
sha256 = "77a402fb577b2e0e5d0bdc1cf9c65278915cdb25171e3452c68b6da8a561f8f0",
build_file = "//bazel:jsoncpp.BUILD",
strip_prefix = "jsoncpp-1.9.2",
urls = [
"https://github.com/open-source-parsers/jsoncpp/archive/1.9.2.tar.gz",
],
)
```
with:
```
git_repository(
name = "jsoncpp_git",
branch = "mglb/bazel-support",
remote = "https://github.com/mglb/jsoncpp.git",
)
```
in `WORKSPACE` file, and then running `bazel clean; bazel test //...`
=> Add support for Bazel build system

src/lib_json/CMakeLists.txt
The minimum version for the project is CMake 3.8.0 (as set in `cmake_minimum_required()` at the top of the root `CMakeLists.txt`), so there's no point in keeping legacy code for pre-3.0 or pre-2.8 CMake.
=> CMake: Remove ancient version checks

example/readFromString/readFromString.cpp, example/streamWrite/streamWrite.cpp
Noticed these two examples use unique_ptr but forgot to include \<memory\>
=> minor fix for code examples

include/json/reader.h
This was introduced in #1149 (and renamed in #1162) but as far as I can tell it was never documented.
=> Document skipBom in CharReaderBuilder

src/lib_json/CMakeLists.txt
This PR just fixed a wrong configuration in the `cmake` files with the `POSITION_INDEPENDENT_CODE`, it should be just enabled when the `BUILD_SHARED_LIBS` config is enabled as well.
The specific details about the issue can be found here:
#1344 
Thanks
=> Fix POSITION_INDEPENDENT_CODE

CMakeLists.txt, include/json/reader.h, include/json/version.h, include/json/writer.h, meson.build
These are only getting in the way. Nobody needs to see these at compile-time (even though I wish people would stop using these).
=> Drop compile-time deprecation warning

include/json/allocator.h, include/json/json_features.h, include/json/reader.h, include/json/value.h, include/json/writer.h
On CHERI, and thus Arm's Morello prototype, pointers are represented as
hardware capabilities. These capabilities are comprised of not just an
integer address, as is the representation for traditional pointers, but
also bounds, permissions and other metadata, plus a tag bit used as the
validity bit, which provides fine-grained spatial and referential safety
for C and C++ in hardware. This tag bit is not part of the data itself
and is instead kept on the side, flowing with the capability between
registers and the memory subsystem, and any attempt to amplify the
privilege of or corrupt a capability clears this tag (or, in some cases,
traps), rendering them impossible to forge; you can only create
capabilities that are (possibly trivial) subsets of existing ones.
When the capability is …
=> Use default rather than hard-coded 8 for maximum aggregate member alignment

include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
This PR adds the `front` and `back` methods to the `Json::Value` class.
These methods can be used to access the first and last elements of a `Json::Value` container.
For a `Json::Value v` they are equal to `*v.begin()` and `*(--v.end())`.
=> feat: adds front and back methods to Value type

CMakeLists.txt
If jsoncpp is a subproject (like a git submodule), setting the global cmake variables affect the entire project (changes the structure of the output folders) and these changes prevent it.
=> Avoid using cmake glob vars if we are a subproject v2

include/json/config.h, include/json/value.h, include/json/version.h, src/lib_json/json_value.cpp, src/test_lib_json/jsontest.cpp, src/test_lib_json/jsontest.h
The Cmake description uses `JSONCPP_USE_SECURE_MEMORY` and the source uses `JSONCPP_USING_SECURE_MEMORY`.
Is it known that the tests don't compile with this setting being enabled?
=> Fix flag -DJSONCPP_USE_SECURE_MEMORY:BOOL=TRUE

jsoncppConfig.cmake.meson.in
fixes #1568
relates to https://github.com/Homebrew/homebrew-core/pull/189352
=> fix(build): remove `check_required_components` for meson build

devtools/batchbuild.py
This lives on on `html` since Python 3.2
https://peps.python.org/pep-0594/
=> the cgi module was removed from Python3.13

src/lib_json/CMakeLists.txt
The change from #1480 broke the name of the static library when targeting MinGW. That lead to a situation where the values in the pkg-config file didn't match the library name. See https://github.com/msys2/MINGW-packages/issues/22584.
Fix the condition to only use the name suffix for the static library when building with MSVC or when targeting MSVC (potentially with another compiler like LLVM Clang).
=> Fix name of static library when targeting MinGW.

src/lib_json/json_value.cpp
The commit in 54fc4e2 introduces several warnings of "**comparison of integer expressions of different signedness: 'unsigned int' and 'int'**". Example:
```
src/./json/json_value.cpp: In instantiation of 'bool Json::InRange(double, T, U) [with T = int; U = unsigned int]':
src/./json/json_value.cpp:687:5:   required from here
src/./json/json_value.cpp:106:30: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
106 |          !(static_cast<U>(d) == min && d != integerToDouble(min));
|            ~~~~~~~~~~~~~~~~~~^~~~~~
```
This is because `maxUInt` is `unsigned` while the `0` literal is not.
I replaced them with `0u` and it looks fine again.
=> Fix comparison warnings caused by 54fc4e2

AUTHORS, src/lib_json/json_reader.cpp, src/lib_json/json_writer.cpp
We already assume C++11 elsewhere (using `unique_ptr`, etc) so all pre-11 `#ifdef` branches are dead code at this point. Fixes issue #1591 because we can just use `std::isfinite` and `std::isnan`.
=> Drop pre-C++11 alternatives

include/json/value.h, src/lib_json/json_value.cpp
This adds direct support for `std::string_view` when available (C++17 and above). The current API can be used with `std::string_view` via the low-level two-pointer methods, but is not ergonomic. E.g., compare:
```
Json::Value node;
std::string foo, bar, baz;
std::string_view foo_sv, bar_sv, baz_sv;
// Efficient & readable:
node[foo][bar][baz];
// Less efficient, less readable:
node[std::string(foo_sv)][std::string(bar_sv)][std::string(baz_sv)];
// Efficient, but a lot less readable:
*node.demand(foo_sv.data(), foo_sv.data() + foo_sv.size())
->demand(bar_sv.data(), bar_sv.data() + bar_sv.size())
->demand(baz_sv.data(), baz_sv.data() + baz_sv.size());
// After this change, efficient & readable:
node[foo_sv][bar_sv][baz_sv];
```
*   The constructor can take a `std::string_view` parameter. …
=> feat: support std::string_view in Value API

include/json/value.h, src/lib_json/json_value.cpp, src/test_lib_json/main.cpp
This adds a convenience function to return a member if it has a specific json type. All `isType` values are supported.
=> Added Value::findType with String key

.gitignore, CMakeLists.txt, MODULE.bazel, include/json/version.h, meson.build
Notes:
---
1) This likely doesn't require a release note as it _shouldn't_ have any effect on any released product.
1) The `MODULE.bazel` is forked from the "[bazel-central-registry](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/jsoncpp/1.9.6/MODULE.bazel)" and this allows the BCR to quit having to uses patches.
1) With these changes JsonCpp can be built by Bazel without any changes. Without this, Bazel is unable to locate a correct root to build from and fails.
1) This effectively supersede https://github.com/open-source-parsers/jsoncpp/pull/1534 ;; Addressing comments from there:
1) The version in `MODULE.bazel` should track the version used everywhere else. This just becomes yet-another-copy of that.
1) `WORKSPACE` is dead (though one _would_ be needed ... if …
=> Set up for Bazel module builds.

example/BUILD.bazel
This is more OCD than anything, but there is a `CMakeList` so might as well do this as well. 
All 5 rules work under `bazel run` (and also do so under all configs enabled via https://github.com/open-source-parsers/jsoncpp/pull/1600 ).
=> Add a BUILD.bazel file for //example.
